# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6df58cff97dafffef2606884c41d41b465c3615b680e0e1d457915261828a2b7a21eb2a907672e948539222ed8842e88fd56e5fd6cf17be166346e22ed34163

test:
  secret_key_base: 5bc2f6f76154f8c62e9638e41e21ee62e0e1f57853e67c7332dca09f456943934860cd217e919d1d34b500ec74e2edd50de7f898c005c2e3bf82bddc491e477f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
